### ISSUE TITLE
deprecated as of 3.4.4146. Use add_tag instead

### ISSUE THREAD

**Issue by lst-oss** [Martyx00/VulnFanatic#22]
Hi! When I run the tool, the following problem occurs:

[Default] C:\Users\aaa\AppData\Roaming\Binary Ninja\plugins\VulnFanatic\scanner\scanner31.py:102: DeprecatedWarning: create_tag is deprecated as of 3.4.4146. Use add_tag instead.
[Default]   tag = xref.function.source_function.create_tag(self.current_view.tag_types["[VulnFanatic] "+conf], f'{test["name"]}: {test["details"]}\n', True)
[Default] D:\Program Files\Vector35\BinaryNinja\plugins\..\python\binaryninja\function.py:799: DeprecatedWarning: create_tag is deprecated as of 3.4.4146. Use add_tag instead
[Default]   return self.view.create_tag(type, data, auto)
[Default] C:\Users\...\AppData\Roaming\Binary Ninja\plugins\VulnFanatic\scanner\scanner31.py:103: DeprecatedWarning: add_user_address_tag is deprecated as of 3.4.4146. Use add_tag instead.
[Default]   xref.function.source_function.add_user_address_tag(xref.address, tag)

This is a version issue. Binaryninja3.5+ replaces some of the list apis like `create_tag` with `add_tag`. 
We can also find clues in the official documents. However, when I try to change the api, I get more errors.
Can you help solve this problem？

Best regards,
lst-oss

**Comment by Martyx00** [comment]
I have updated the code. This should be fixed in 3.6, keep in mind that this plugin will be obsolete with a SIdeKick release as it can completely replace it (I will be publishing some SideKick code to repalce it eventually).
