### ISSUE TITLE
AssertionError: no comparison for types 

### ISSUE THREAD

**Issue by Stankye** [Martyx00/VulnFanatic#23]
[Default] Exception in thread Thread-6:
[Default] Traceback (most recent call last):
[Default]   File "threading.py", line 1016, in _bootstrap_inner
[Default]   File "C:\Users\user\AppData\Local\Programs\Vector35\BinaryNinja\plugins\..\python\binaryninja\plugin.py", line 1056, in run
[Default]     self.task.run()
[Default]   File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\community\plugins\Martyx00_VulnFanatic\scanner\scanner31.py", line 33, in run
[Default]     self.evaluate_results(self.trace(xref,function["trace_params"]),function["function_name"],xref)
[Default]   File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\community\plugins\Martyx00_VulnFanatic\scanner\scanner31.py", line 215, in trace
[Default]     if self.is_in_operands(param,self.expand_postfix_operands(instruction.condition)):
[Default]   File "C:\Users\user\AppData\Roaming\Binary Ninja\repositories\community\plugins\Martyx00_VulnFanatic\scanner\scanner31.py", line 495, in is_in_operands
[Default]     if operands[i:i+len(op)] == op:
[Default]   File "C:\Users\user\AppData\Local\Programs\Vector35\BinaryNinja\plugins\..\python\binaryninja\variable.py", line 83, in __eq__
[Default]     assert False, f"no comparison for types {repr(self)} and {repr(other)}"
[Default] AssertionError: no comparison for types <ConstantData: {zx.16(0x0)}> and <var int32_t* rax_11>

[ControlServer.zip](https://github.com/user-attachments/files/16773533/ControlServer.zip)
password: hunter2

**Comment by Martyx00** [comment]
Fixed in latest commit for master branch. Update in the plugin repo is on the way.
